import { Router } from 'express';
import { listDepartments, listOfficers, reassignOfficerDepartment, getStats, getClearanceOverview, getFlaggedItems, getUncoveredDepartments, getAnalytics } from './admin.controller.js';
import authenticate from '../../middleware/authenticate.js';
import authorize from '../../middleware/authorize.js';
const router = Router();
router.get('/departments', authenticate, authorize(['ADMIN']), listDepartments);
router.get('/officers', authenticate, authorize(['ADMIN']), listOfficers);
router.patch('/officers/:id/department', authenticate, authorize(['ADMIN']), reassignOfficerDepartment);
router.get('/stats', authenticate, authorize(['ADMIN']), getStats);
router.get('/clearance-overview', authenticate, authorize(['ADMIN']), getClearanceOverview);
router.get('/flagged-items', authenticate, authorize(['ADMIN']), getFlaggedItems);
router.get('/uncovered-departments', authenticate, authorize(['ADMIN']), getUncoveredDepartments);
router.get('/analytics', authenticate, authorize(['ADMIN']), getAnalytics);
export default router;