-- 1. GLOBAL IDENTITY LAYER
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  id_number TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT CHECK(role IN ('STUDENT', 'OFFICER', 'ADMIN')) NOT NULL,
  department_assigned_id INTEGER NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. INSTITUTIONAL STRUCTURE LAYER
CREATE TABLE IF NOT EXISTS departments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  sequence_order INTEGER NOT NULL UNIQUE,
  department_type TEXT CHECK(department_type IN ('UNIVERSAL', 'SCHOOL')) NOT NULL DEFAULT 'UNIVERSAL',
  school_code TEXT NULL
);

-- 3. WORKFLOW TRACKING MASTER LAYER
CREATE TABLE IF NOT EXISTS clearance_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_id INTEGER NOT NULL,
  overall_status TEXT CHECK(overall_status IN ('ACTIVE', 'APPROVED', 'FLAGGED')) DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(student_id), -- BULLETPROOF RACE CONDITION SHIELD
  FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 4. GRANULAR WORKFLOW NODE LAYER
CREATE TABLE IF NOT EXISTS dept_clearance_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  request_id INTEGER NOT NULL,
  department_id INTEGER NOT NULL,
  status TEXT CHECK(status IN ('PENDING', 'APPROVED', 'FLAGGED')) DEFAULT 'PENDING',
  remarks TEXT DEFAULT 'Awaiting administrative review.',
  actioned_by_officer_id INTEGER NULL,
  actioned_at TIMESTAMP NULL,
  UNIQUE(request_id, department_id),
  FOREIGN KEY (request_id) REFERENCES clearance_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE,
  FOREIGN KEY (actioned_by_officer_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 5. TRACEABLE AUDIT LAYER
CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  actor_id INTEGER NOT NULL,
  action_type TEXT NOT NULL,
  entity_affected TEXT NOT NULL,
  details TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 6. SYSTEM OVERLAY NOTIFICATION LAYER
CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read INTEGER CHECK(is_read IN (0, 1)) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 7. CLOSING ENTITY CAPTURE LAYER
CREATE TABLE IF NOT EXISTS certificates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  request_id INTEGER NOT NULL UNIQUE,
  file_path TEXT NOT NULL,
  issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (request_id) REFERENCES clearance_requests(id) ON DELETE CASCADE
);